FROM debian:bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
      python3 python3-venv python3-dev binutils \
      gcc libc6-dev linux-libc-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src
